#!/bin/bash

# This script isn't used anymore, it only serves as reference for keeping track
# of which files were deleted to easily add them back if needed.

pushd /wine-install/usr/local

rm -r share/applications
rm -r share/man
rm -r include

# share
rm share/wine/nls/c_10000.nls
rm share/wine/nls/c_10001.nls
rm share/wine/nls/c_10002.nls
rm share/wine/nls/c_10003.nls
rm share/wine/nls/c_10004.nls
rm share/wine/nls/c_10005.nls
rm share/wine/nls/c_10006.nls
rm share/wine/nls/c_10007.nls
rm share/wine/nls/c_10008.nls
rm share/wine/nls/c_10010.nls
rm share/wine/nls/c_10017.nls
rm share/wine/nls/c_10021.nls
rm share/wine/nls/c_10029.nls
rm share/wine/nls/c_10079.nls
rm share/wine/nls/c_10081.nls
rm share/wine/nls/c_10082.nls
rm share/wine/nls/c_1026.nls
rm share/wine/nls/c_1250.nls
rm share/wine/nls/c_1251.nls
rm share/wine/nls/c_1253.nls
rm share/wine/nls/c_1254.nls
rm share/wine/nls/c_1255.nls
rm share/wine/nls/c_1256.nls
rm share/wine/nls/c_1257.nls
rm share/wine/nls/c_1258.nls
rm share/wine/nls/c_1361.nls
rm share/wine/nls/c_20866.nls
rm share/wine/nls/c_20932.nls
rm share/wine/nls/c_20949.nls
rm share/wine/nls/c_21866.nls
rm share/wine/nls/c_28591.nls
rm share/wine/nls/c_28592.nls
rm share/wine/nls/c_28593.nls
rm share/wine/nls/c_28594.nls
rm share/wine/nls/c_28595.nls
rm share/wine/nls/c_28596.nls
rm share/wine/nls/c_28597.nls
rm share/wine/nls/c_28598.nls
rm share/wine/nls/c_28599.nls
rm share/wine/nls/c_28603.nls
rm share/wine/nls/c_28605.nls
rm share/wine/nls/c_500.nls
rm share/wine/nls/c_708.nls
rm share/wine/nls/c_720.nls
rm share/wine/nls/c_737.nls
rm share/wine/nls/c_775.nls
rm share/wine/nls/c_850.nls
rm share/wine/nls/c_852.nls
rm share/wine/nls/c_855.nls
rm share/wine/nls/c_857.nls
rm share/wine/nls/c_860.nls
rm share/wine/nls/c_861.nls
rm share/wine/nls/c_862.nls
rm share/wine/nls/c_863.nls
rm share/wine/nls/c_864.nls
rm share/wine/nls/c_865.nls
rm share/wine/nls/c_866.nls
rm share/wine/nls/c_869.nls
rm share/wine/nls/c_874.nls
rm share/wine/nls/c_875.nls
rm share/wine/nls/c_932.nls
rm share/wine/nls/c_936.nls
rm share/wine/nls/c_949.nls
rm share/wine/nls/c_950.nls
rm share/wine/nls/normidna.nls
rm share/wine/nls/normnfc.nls
rm share/wine/nls/normnfd.nls
rm share/wine/nls/normnfkc.nls
rm share/wine/nls/normnfkd.nls

# Removing everything except wine and wineserver
mv bin bin-bkp
mkdir bin
mv bin-bkp/wine bin
mv bin-bkp/wineserver bin
rm -r bin-bkp

# lib/i386-unix
rm lib/wine/i386-unix/xinput*
rm lib/wine/i386-unix/xaudio*
rm lib/wine/i386-unix/x3daudio*
rm lib/wine/i386-unix/xactengine*
rm lib/wine/i386-unix/xapofx*
rm lib/wine/i386-unix/*d3d*
rm lib/wine/i386-unix/*vulkan*
rm lib/wine/i386-unix/acledit.dll.so
rm lib/wine/i386-unix/aclui.dll.so
rm lib/wine/i386-unix/activeds.dll.so
rm lib/wine/i386-unix/actxprxy.dll.so
rm lib/wine/i386-unix/adsldp.dll.so
rm lib/wine/i386-unix/adsldpc.dll.so
rm lib/wine/i386-unix/amsi.dll.so
rm lib/wine/i386-unix/amstream.dll.so
rm lib/wine/i386-unix/apphelp.dll.so
rm lib/wine/i386-unix/appwiz.cpl.so
rm lib/wine/i386-unix/appxdeploymentclient.dll.so
rm lib/wine/i386-unix/arp.exe.so
rm lib/wine/i386-unix/aspnet_regiis.exe.so
rm lib/wine/i386-unix/atl.dll.so
rm lib/wine/i386-unix/atl110.dll.so
rm lib/wine/i386-unix/atl80.dll.so
rm lib/wine/i386-unix/atl90.dll.so
rm lib/wine/i386-unix/atlthunk.dll.so
rm lib/wine/i386-unix/atmlib.dll.so
rm lib/wine/i386-unix/attrib.exe.so
rm lib/wine/i386-unix/authz.dll.so
rm lib/wine/i386-unix/avicap32.dll.so
rm lib/wine/i386-unix/avicap32.so
rm lib/wine/i386-unix/avifil32.dll.so
rm lib/wine/i386-unix/avrt.dll.so
rm lib/wine/i386-unix/bcp47langs.dll.so
rm lib/wine/i386-unix/bcrypt.so
rm lib/wine/i386-unix/bcryptprimitives.dll.so
rm lib/wine/i386-unix/bluetoothapis.dll.so
rm lib/wine/i386-unix/browseui.dll.so
rm lib/wine/i386-unix/bthprops.cpl.so
rm lib/wine/i386-unix/cabarc.exe.so
rm lib/wine/i386-unix/cabinet.dll.so
rm lib/wine/i386-unix/cacls.exe.so
rm lib/wine/i386-unix/cards.dll.so
rm lib/wine/i386-unix/cdosys.dll.so
rm lib/wine/i386-unix/certutil.exe.so
rm lib/wine/i386-unix/cfgmgr32.dll.so
rm lib/wine/i386-unix/chcp.com.so
rm lib/wine/i386-unix/clock.exe.so
rm lib/wine/i386-unix/clusapi.dll.so
rm lib/wine/i386-unix/cmd.exe.so
rm lib/wine/i386-unix/cng.sys.so
rm lib/wine/i386-unix/colorcnv.dll.so
rm lib/wine/i386-unix/comcat.dll.so
rm lib/wine/i386-unix/comctl32.dll.so
rm lib/wine/i386-unix/comctl32_v6.dll.so
rm lib/wine/i386-unix/comdlg32.dll.so
rm lib/wine/i386-unix/comsvcs.dll.so
rm lib/wine/i386-unix/compstui.dll.so
rm lib/wine/i386-unix/concrt140.dll.so
rm lib/wine/i386-unix/connect.dll.so
rm lib/wine/i386-unix/coremessaging.dll.so
rm lib/wine/i386-unix/credui.dll.so
rm lib/wine/i386-unix/crtdll.dll.so
rm lib/wine/i386-unix/cryptdlg.dll.so
rm lib/wine/i386-unix/cryptdll.dll.so
rm lib/wine/i386-unix/cryptext.dll.so
rm lib/wine/i386-unix/cryptnet.dll.so
rm lib/wine/i386-unix/cryptowinrt.dll.so
rm lib/wine/i386-unix/cryptsp.dll.so
rm lib/wine/i386-unix/cryptui.dll.so
rm lib/wine/i386-unix/cryptxml.dll.so
rm lib/wine/i386-unix/cscript.exe.so
rm lib/wine/i386-unix/ctapi32.dll.so
rm lib/wine/i386-unix/ctapi32.so
rm lib/wine/i386-unix/ctl3d32.dll.so
rm lib/wine/i386-unix/d2d1.dll.so
rm lib/wine/i386-unix/dataexchange.dll.so
rm lib/wine/i386-unix/davclnt.dll.so
rm lib/wine/i386-unix/dbgeng.dll.so
rm lib/wine/i386-unix/dbghelp.dll.so
rm lib/wine/i386-unix/dciman32.dll.so
rm lib/wine/i386-unix/dcomp.dll.so
rm lib/wine/i386-unix/ddraw.dll.so
rm lib/wine/i386-unix/ddrawex.dll.so
rm lib/wine/i386-unix/desk.cpl.so
rm lib/wine/i386-unix/devenum.dll.so
rm lib/wine/i386-unix/dhcpcsvc.dll.so
rm lib/wine/i386-unix/dhcpcsvc6.dll.so
rm lib/wine/i386-unix/dhtmled.ocx.so
rm lib/wine/i386-unix/diasymreader.dll.so
rm lib/wine/i386-unix/difxapi.dll.so
rm lib/wine/i386-unix/dinput.dll.so
rm lib/wine/i386-unix/dinput8.dll.so
rm lib/wine/i386-unix/directmanipulation.dll.so
rm lib/wine/i386-unix/dism.exe.so
rm lib/wine/i386-unix/dispex.dll.so
rm lib/wine/i386-unix/dllhost.exe.so
rm lib/wine/i386-unix/dmband.dll.so
rm lib/wine/i386-unix/dmcompos.dll.so
rm lib/wine/i386-unix/dmime.dll.so
rm lib/wine/i386-unix/dmloader.dll.so
rm lib/wine/i386-unix/dmscript.dll.so
rm lib/wine/i386-unix/dmstyle.dll.so
rm lib/wine/i386-unix/dmsynth.dll.so
rm lib/wine/i386-unix/dmusic.dll.so
rm lib/wine/i386-unix/dmusic32.dll.so
rm lib/wine/i386-unix/dnsapi.so
rm lib/wine/i386-unix/dplay.dll.so
rm lib/wine/i386-unix/dplaysvr.exe.so
rm lib/wine/i386-unix/dplayx.dll.so
rm lib/wine/i386-unix/dpnaddr.dll.so
rm lib/wine/i386-unix/dpnet.dll.so
rm lib/wine/i386-unix/dpnhpast.dll.so
rm lib/wine/i386-unix/dpnhupnp.dll.so
rm lib/wine/i386-unix/dpnlobby.dll.so
rm lib/wine/i386-unix/dpnsvr.exe.so
rm lib/wine/i386-unix/dpvoice.dll.so
rm lib/wine/i386-unix/dpvsetup.exe.so
rm lib/wine/i386-unix/dpwsockx.dll.so
rm lib/wine/i386-unix/drmclien.dll.so
rm lib/wine/i386-unix/dsdmo.dll.so
rm lib/wine/i386-unix/dsound.dll.so
rm lib/wine/i386-unix/dsquery.dll.so
rm lib/wine/i386-unix/dssenh.dll.so
rm lib/wine/i386-unix/dsuiext.dll.so
rm lib/wine/i386-unix/dswave.dll.so
rm lib/wine/i386-unix/dwmapi.dll.so
rm lib/wine/i386-unix/dwrite.dll.so
rm lib/wine/i386-unix/dwrite.so
rm lib/wine/i386-unix/dx8vb.dll.so
rm lib/wine/i386-unix/dxcore.dll.so
rm lib/wine/i386-unix/dxdiag.exe.so
rm lib/wine/i386-unix/dxdiagn.dll.so
rm lib/wine/i386-unix/dxgi.dll.so
rm lib/wine/i386-unix/dxtrans.dll.so
rm lib/wine/i386-unix/dxva2.dll.so
rm lib/wine/i386-unix/eject.exe.so
rm lib/wine/i386-unix/esent.dll.so
rm lib/wine/i386-unix/evr.dll.so
rm lib/wine/i386-unix/expand.exe.so
rm lib/wine/i386-unix/explorerframe.dll.so
rm lib/wine/i386-unix/extrac32.exe.so
rm lib/wine/i386-unix/faultrep.dll.so
rm lib/wine/i386-unix/fc.exe.so
rm lib/wine/i386-unix/feclient.dll.so
rm lib/wine/i386-unix/find.exe.so
rm lib/wine/i386-unix/findstr.exe.so
rm lib/wine/i386-unix/fltlib.dll.so
rm lib/wine/i386-unix/fltmgr.sys.so
rm lib/wine/i386-unix/fntcache.dll.so
rm lib/wine/i386-unix/fontsub.dll.so
rm lib/wine/i386-unix/fsutil.exe.so
rm lib/wine/i386-unix/fusion.dll.so
rm lib/wine/i386-unix/fwpuclnt.dll.so
rm lib/wine/i386-unix/gameinput.dll.so
rm lib/wine/i386-unix/gameux.dll.so
rm lib/wine/i386-unix/gamingtcui.dll.so
rm lib/wine/i386-unix/gdiplus.dll.so
rm lib/wine/i386-unix/geolocation.dll.so
rm lib/wine/i386-unix/glu32.dll.so
rm lib/wine/i386-unix/gpkcsp.dll.so
rm lib/wine/i386-unix/graphicscapture.dll.so
rm lib/wine/i386-unix/hal.dll.so
rm lib/wine/i386-unix/hh.exe.so
rm lib/wine/i386-unix/hhctrl.ocx.so
rm lib/wine/i386-unix/hid.dll.so
rm lib/wine/i386-unix/hidclass.sys.so
rm lib/wine/i386-unix/hidparse.sys.so
rm lib/wine/i386-unix/hlink.dll.so
rm lib/wine/i386-unix/hnetcfg.dll.so
rm lib/wine/i386-unix/hostname.exe.so
rm lib/wine/i386-unix/hrtfapo.dll.so
rm lib/wine/i386-unix/http.sys.so
rm lib/wine/i386-unix/httpapi.dll.so
rm lib/wine/i386-unix/hvsimanagementapi.dll.so
rm lib/wine/i386-unix/ia2comproxy.dll.so
rm lib/wine/i386-unix/icacls.exe.so
rm lib/wine/i386-unix/iccvid.dll.so
rm lib/wine/i386-unix/icinfo.exe.so
rm lib/wine/i386-unix/icmui.dll.so
rm lib/wine/i386-unix/ieframe.dll.so
rm lib/wine/i386-unix/ieproxy.dll.so
rm lib/wine/i386-unix/iertutil.dll.so
rm lib/wine/i386-unix/iexplore.exe.so
rm lib/wine/i386-unix/imaadp32.acm.so
rm lib/wine/i386-unix/imm32.dll.so
rm lib/wine/i386-unix/inetcomm.dll.so
rm lib/wine/i386-unix/inetcpl.cpl.so
rm lib/wine/i386-unix/inetmib1.dll.so
rm lib/wine/i386-unix/infosoft.dll.so
rm lib/wine/i386-unix/initpki.dll.so
rm lib/wine/i386-unix/inkobj.dll.so
rm lib/wine/i386-unix/inseng.dll.so
rm lib/wine/i386-unix/ipconfig.exe.so
rm lib/wine/i386-unix/iprop.dll.so
rm lib/wine/i386-unix/ir50_32.dll.so
rm lib/wine/i386-unix/irprops.cpl.so
rm lib/wine/i386-unix/itircl.dll.so
rm lib/wine/i386-unix/itss.dll.so
rm lib/wine/i386-unix/joy.cpl.so
rm lib/wine/i386-unix/jscript.dll.so
rm lib/wine/i386-unix/jsproxy.dll.so
rm lib/wine/i386-unix/kerberos.dll.so
rm lib/wine/i386-unix/kerberos.so
rm lib/wine/i386-unix/klist.exe.so
rm lib/wine/i386-unix/ksecdd.sys.so
rm lib/wine/i386-unix/ksproxy.ax.so
rm lib/wine/i386-unix/ksuser.dll.so
rm lib/wine/i386-unix/ktmw32.dll.so
rm lib/wine/i386-unix/l3codeca.acm.so
rm lib/wine/i386-unix/l3codecx.ax.so
rm lib/wine/i386-unix/libaclui.a
rm lib/wine/i386-unix/libactiveds.a
rm lib/wine/i386-unix/libadsiid.a
rm lib/wine/i386-unix/libadvapi32.a
rm lib/wine/i386-unix/libadvpack.a
rm lib/wine/i386-unix/libatl.a
rm lib/wine/i386-unix/libatl100.a
rm lib/wine/i386-unix/libatl110.a
rm lib/wine/i386-unix/libatl80.a
rm lib/wine/i386-unix/libatlthunk.a
rm lib/wine/i386-unix/libavicap32.a
rm lib/wine/i386-unix/libavifil32.a
rm lib/wine/i386-unix/libavrt.a
rm lib/wine/i386-unix/libbcp47langs.a
rm lib/wine/i386-unix/libbcrypt.a
rm lib/wine/i386-unix/libbluetoothapis.a
rm lib/wine/i386-unix/libcabinet.a
rm lib/wine/i386-unix/libcards.a
rm lib/wine/i386-unix/libcfgmgr32.a
rm lib/wine/i386-unix/libclusapi.a
rm lib/wine/i386-unix/libcombase.a
rm lib/wine/i386-unix/libcomctl32.a
rm lib/wine/i386-unix/libcomdlg32.a
rm lib/wine/i386-unix/libcoml2.a
rm lib/wine/i386-unix/libcompstui.a
rm lib/wine/i386-unix/libcomsvcs.a
rm lib/wine/i386-unix/libcoremessaging.a
rm lib/wine/i386-unix/libcredui.a
rm lib/wine/i386-unix/libcrypt32.a
rm lib/wine/i386-unix/libcryptdll.a
rm lib/wine/i386-unix/libcryptnet.a
rm lib/wine/i386-unix/libcryptsp.a
rm lib/wine/i386-unix/libcryptui.a
rm lib/wine/i386-unix/libcryptxml.a
rm lib/wine/i386-unix/libd2d1.a
rm lib/wine/i386-unix/libdbgeng.a
rm lib/wine/i386-unix/libdbghelp.a
rm lib/wine/i386-unix/libdciman32.a
rm lib/wine/i386-unix/libddraw.a
rm lib/wine/i386-unix/libdhcpcsvc.a
rm lib/wine/i386-unix/libdinput.a
rm lib/wine/i386-unix/libdinput8.a
rm lib/wine/i386-unix/libdmoguids.a
rm lib/wine/i386-unix/libdnsapi.a
rm lib/wine/i386-unix/libdplayx.a
rm lib/wine/i386-unix/libdpnet.a
rm lib/wine/i386-unix/libdsound.a
rm lib/wine/i386-unix/libdwmapi.a
rm lib/wine/i386-unix/libdwrite.a
rm lib/wine/i386-unix/libdxerr8.a
rm lib/wine/i386-unix/libdxerr9.a
rm lib/wine/i386-unix/libdxgi.a
rm lib/wine/i386-unix/libdxguid.a
rm lib/wine/i386-unix/libdxva2.a
rm lib/wine/i386-unix/libevr.a
rm lib/wine/i386-unix/libfaultrep.a
rm lib/wine/i386-unix/libfltmgr.a
rm lib/wine/i386-unix/libgdi32.a
rm lib/wine/i386-unix/libgdiplus.a
rm lib/wine/i386-unix/libglu32.a
rm lib/wine/i386-unix/libhal.a
rm lib/wine/i386-unix/libhid.a
rm lib/wine/i386-unix/libhidclass.a
rm lib/wine/i386-unix/libhidparse.a
rm lib/wine/i386-unix/libhlink.a
rm lib/wine/i386-unix/libhtmlhelp.a
rm lib/wine/i386-unix/libhttpapi.a
rm lib/wine/i386-unix/libicmui.a
rm lib/wine/i386-unix/libieframe.a
rm lib/wine/i386-unix/libimagehlp.a
rm lib/wine/i386-unix/libimm32.a
rm lib/wine/i386-unix/libinetcomm.a
rm lib/wine/i386-unix/libiphlpapi.a
rm lib/wine/i386-unix/libjsproxy.a
rm lib/wine/i386-unix/libkernel32.a
rm lib/wine/i386-unix/libkernelbase.a
rm lib/wine/i386-unix/libloadperf.a
rm lib/wine/i386-unix/liblz32.a
rm lib/wine/i386-unix/libmapi32.a
rm lib/wine/i386-unix/libmf.a
rm lib/wine/i386-unix/libmfplat.a
rm lib/wine/i386-unix/libmfplay.a
rm lib/wine/i386-unix/libmfreadwrite.a
rm lib/wine/i386-unix/libmfsrcsnk.a
rm lib/wine/i386-unix/libmfuuid.a
rm lib/wine/i386-unix/libmlang.a
rm lib/wine/i386-unix/libmpr.a
rm lib/wine/i386-unix/libmprapi.a
rm lib/wine/i386-unix/libmsacm32.a
rm lib/wine/i386-unix/libmsasn1.a
rm lib/wine/i386-unix/libmscms.a
rm lib/wine/i386-unix/libmsdmo.a
rm lib/wine/i386-unix/libmshtml.a
rm lib/wine/i386-unix/libmsi.a
rm lib/wine/i386-unix/libmsimg32.a
rm lib/wine/i386-unix/libmspatcha.a
rm lib/wine/i386-unix/libmsvcp140.a
rm lib/wine/i386-unix/libmsvcr100.a
rm lib/wine/i386-unix/libmsvcr110.a
rm lib/wine/i386-unix/libmsvcr120.a
rm lib/wine/i386-unix/libmsvcr70.a
rm lib/wine/i386-unix/libmsvcr71.a
rm lib/wine/i386-unix/libmsvcr80.a
rm lib/wine/i386-unix/libmsvcr90.a
rm lib/wine/i386-unix/libmsvcrt.a
rm lib/wine/i386-unix/libmsvcrtd.a
rm lib/wine/i386-unix/libmsvfw32.a
rm lib/wine/i386-unix/libmswsock.a
rm lib/wine/i386-unix/libncrypt.a
rm lib/wine/i386-unix/libnddeapi.a
rm lib/wine/i386-unix/libnetapi32.a
rm lib/wine/i386-unix/libnetio.a
rm lib/wine/i386-unix/libnetutils.a
rm lib/wine/i386-unix/libnewdev.a
rm lib/wine/i386-unix/libninput.a
rm lib/wine/i386-unix/libnormaliz.a
rm lib/wine/i386-unix/libnsi.a
rm lib/wine/i386-unix/libntdll.a
rm lib/wine/i386-unix/libntdsapi.a
rm lib/wine/i386-unix/libntoskrnl.a
rm lib/wine/i386-unix/libodbc32.a
rm lib/wine/i386-unix/libodbccp32.a
rm lib/wine/i386-unix/libole32.a
rm lib/wine/i386-unix/liboleacc.a
rm lib/wine/i386-unix/liboleaut32.a
rm lib/wine/i386-unix/libolecli32.a
rm lib/wine/i386-unix/liboledlg.a
rm lib/wine/i386-unix/libolepro32.a
rm lib/wine/i386-unix/libolesvr32.a
rm lib/wine/i386-unix/libopengl32.a
rm lib/wine/i386-unix/libpdh.a
rm lib/wine/i386-unix/libpowrprof.a
rm lib/wine/i386-unix/libprntvpt.a
rm lib/wine/i386-unix/libpropsys.a
rm lib/wine/i386-unix/libpsapi.a
rm lib/wine/i386-unix/libquartz.a
rm lib/wine/i386-unix/libqwave.a
rm lib/wine/i386-unix/librasapi32.a
rm lib/wine/i386-unix/librasdlg.a
rm lib/wine/i386-unix/libresutils.a
rm lib/wine/i386-unix/libriched20.a
rm lib/wine/i386-unix/librometadata.a
rm lib/wine/i386-unix/librpcrt4.a
rm lib/wine/i386-unix/librsaenh.a
rm lib/wine/i386-unix/librtutils.a
rm lib/wine/i386-unix/librtworkq.a
rm lib/wine/i386-unix/libscrrun.a
rm lib/wine/i386-unix/libsechost.a
rm lib/wine/i386-unix/libsecur32.a
rm lib/wine/i386-unix/libsensapi.a
rm lib/wine/i386-unix/libsetupapi.a
rm lib/wine/i386-unix/libsfc.a
rm lib/wine/i386-unix/libsfc_os.a
rm lib/wine/i386-unix/libshcore.a
rm lib/wine/i386-unix/libshdocvw.a
rm lib/wine/i386-unix/libshell32.a
rm lib/wine/i386-unix/libshfolder.a
rm lib/wine/i386-unix/libshlwapi.a
rm lib/wine/i386-unix/libslc.a
rm lib/wine/i386-unix/libsnmpapi.a
rm lib/wine/i386-unix/libspoolss.a
rm lib/wine/i386-unix/libsti.a
rm lib/wine/i386-unix/libstrmbase.a
rm lib/wine/i386-unix/libstrmiids.a
rm lib/wine/i386-unix/libsxs.a
rm lib/wine/i386-unix/libt2embed.a
rm lib/wine/i386-unix/libtapi32.a
rm lib/wine/i386-unix/libtdh.a
rm lib/wine/i386-unix/libtwaindsm.a
rm lib/wine/i386-unix/libucrtbase.a
rm lib/wine/i386-unix/libuiautomationcore.a
rm lib/wine/i386-unix/libunicows.a
rm lib/wine/i386-unix/liburl.a
rm lib/wine/i386-unix/liburlmon.a
rm lib/wine/i386-unix/libusbd.a
rm lib/wine/i386-unix/libuser32.a
rm lib/wine/i386-unix/libuserenv.a
rm lib/wine/i386-unix/libusp10.a
rm lib/wine/i386-unix/libuuid.a
rm lib/wine/i386-unix/libuxtheme.a
rm lib/wine/i386-unix/libvcruntime140.a
rm lib/wine/i386-unix/libvdmdbg.a
rm lib/wine/i386-unix/libversion.a
rm lib/wine/i386-unix/libwbemuuid.a
rm lib/wine/i386-unix/libwebservices.a
rm lib/wine/i386-unix/libwer.a
rm lib/wine/i386-unix/libwevtapi.a
rm lib/wine/i386-unix/libwin32u.a
rm lib/wine/i386-unix/libwindowscodecs.a
rm lib/wine/i386-unix/libwindowscodecsext.a
rm lib/wine/i386-unix/libwinecrt0.a
rm lib/wine/i386-unix/libwinedmo.a
rm lib/wine/i386-unix/libwing32.a
rm lib/wine/i386-unix/libwinhttp.a
rm lib/wine/i386-unix/libwininet.a
rm lib/wine/i386-unix/libwinmm.a
rm lib/wine/i386-unix/libwinnls32.a
rm lib/wine/i386-unix/libwinspool.a
rm lib/wine/i386-unix/libwintab32.a
rm lib/wine/i386-unix/libwintrust.a
rm lib/wine/i386-unix/libwintypes.a
rm lib/wine/i386-unix/libwlanapi.a
rm lib/wine/i386-unix/libwldap32.a
rm lib/wine/i386-unix/libwmcodecdspuuid.a
rm lib/wine/i386-unix/libwmvcore.a
rm lib/wine/i386-unix/libwnaspi32.a
rm lib/wine/i386-unix/libws2_32.a
rm lib/wine/i386-unix/libwsdapi.a
rm lib/wine/i386-unix/libwsnmp32.a
rm lib/wine/i386-unix/libwsock32.a
rm lib/wine/i386-unix/libwtsapi32.a
rm lib/wine/i386-unix/libxaudio2_8.a
rm lib/wine/i386-unix/libxinput.a
rm lib/wine/i386-unix/libxmllite.a
rm lib/wine/i386-unix/loadperf.dll.so
rm lib/wine/i386-unix/localspl.dll.so
rm lib/wine/i386-unix/localspl.so
rm lib/wine/i386-unix/localui.dll.so
rm lib/wine/i386-unix/lodctr.exe.so
rm lib/wine/i386-unix/magnification.dll.so
rm lib/wine/i386-unix/makecab.exe.so
rm lib/wine/i386-unix/mapi32.dll.so
rm lib/wine/i386-unix/mapistub.dll.so
rm lib/wine/i386-unix/mciavi32.dll.so
rm lib/wine/i386-unix/mcicda.dll.so
rm lib/wine/i386-unix/mciqtz32.dll.so
rm lib/wine/i386-unix/mciseq.dll.so
rm lib/wine/i386-unix/mciwave.dll.so
rm lib/wine/i386-unix/mf.dll.so
rm lib/wine/i386-unix/mf3216.dll.so
rm lib/wine/i386-unix/mfasfsrcsnk.dll.so
rm lib/wine/i386-unix/mfh264enc.dll.so
rm lib/wine/i386-unix/mfmediaengine.dll.so
rm lib/wine/i386-unix/mfmp4srcsnk.dll.so
rm lib/wine/i386-unix/mfplat.dll.so
rm lib/wine/i386-unix/mfplay.dll.so
rm lib/wine/i386-unix/mfreadwrite.dll.so
rm lib/wine/i386-unix/mfsrcsnk.dll.so
rm lib/wine/i386-unix/mgmtapi.dll.so
rm lib/wine/i386-unix/midimap.dll.so
rm lib/wine/i386-unix/mlang.dll.so
rm lib/wine/i386-unix/mmcndmgr.dll.so
rm lib/wine/i386-unix/mmdevapi.dll.so
rm lib/wine/i386-unix/mofcomp.exe.so
rm lib/wine/i386-unix/mouhid.sys.so
rm lib/wine/i386-unix/mountmgr.so
rm lib/wine/i386-unix/mountmgr.sys.so
rm lib/wine/i386-unix/mp3dmod.dll.so
rm lib/wine/i386-unix/mprapi.dll.so
rm lib/wine/i386-unix/msacm32.dll.so
rm lib/wine/i386-unix/msacm32.drv.so
rm lib/wine/i386-unix/msado15.dll.so
rm lib/wine/i386-unix/msadp32.acm.so
rm lib/wine/i386-unix/msasn1.dll.so
rm lib/wine/i386-unix/msauddecmft.dll.so
rm lib/wine/i386-unix/mscat32.dll.so
rm lib/wine/i386-unix/mscms.dll.so
rm lib/wine/i386-unix/mscorwks.dll.so
rm lib/wine/i386-unix/msctf.dll.so
rm lib/wine/i386-unix/msctfmonitor.dll.so
rm lib/wine/i386-unix/msctfp.dll.so
rm lib/wine/i386-unix/msdaps.dll.so
rm lib/wine/i386-unix/msdasql.dll.so
rm lib/wine/i386-unix/msdelta.dll.so
rm lib/wine/i386-unix/msdmo.dll.so
rm lib/wine/i386-unix/msdrm.dll.so
rm lib/wine/i386-unix/msftedit.dll.so
rm lib/wine/i386-unix/msg711.acm.so
rm lib/wine/i386-unix/msgsm32.acm.so
rm lib/wine/i386-unix/mshta.exe.so
rm lib/wine/i386-unix/mshtml.dll.so
rm lib/wine/i386-unix/msi.dll.so
rm lib/wine/i386-unix/msidb.exe.so
rm lib/wine/i386-unix/msident.dll.so
rm lib/wine/i386-unix/msiexec.exe.so
rm lib/wine/i386-unix/msimg32.dll.so
rm lib/wine/i386-unix/msimtf.dll.so
rm lib/wine/i386-unix/msinfo32.exe.so
rm lib/wine/i386-unix/msisip.dll.so
rm lib/wine/i386-unix/msisys.ocx.so
rm lib/wine/i386-unix/msls31.dll.so
rm lib/wine/i386-unix/msmpeg2vdec.dll.so
rm lib/wine/i386-unix/msnet32.dll.so
rm lib/wine/i386-unix/mspatcha.dll.so
rm lib/wine/i386-unix/msports.dll.so
rm lib/wine/i386-unix/msrle32.dll.so
rm lib/wine/i386-unix/msscript.ocx.so
rm lib/wine/i386-unix/mssign32.dll.so
rm lib/wine/i386-unix/mssip32.dll.so
rm lib/wine/i386-unix/mstask.dll.so
rm lib/wine/i386-unix/msttsengine.dll.so
rm lib/wine/i386-unix/msvcirt.dll.so
rm lib/wine/i386-unix/msvcm80.dll.so
rm lib/wine/i386-unix/msvcm90.dll.so
rm lib/wine/i386-unix/msvcp100.dll.so
rm lib/wine/i386-unix/msvcp110.dll.so
rm lib/wine/i386-unix/msvcp120.dll.so
rm lib/wine/i386-unix/msvcp120_app.dll.so
rm lib/wine/i386-unix/msvcp140.dll.so
rm lib/wine/i386-unix/msvcp140_1.dll.so
rm lib/wine/i386-unix/msvcp140_2.dll.so
rm lib/wine/i386-unix/msvcp140_atomic_wait.dll.so
rm lib/wine/i386-unix/msvcp140_codecvt_ids.dll.so
rm lib/wine/i386-unix/msvcp60.dll.so
rm lib/wine/i386-unix/msvcp70.dll.so
rm lib/wine/i386-unix/msvcp71.dll.so
rm lib/wine/i386-unix/msvcp80.dll.so
rm lib/wine/i386-unix/msvcp90.dll.so
rm lib/wine/i386-unix/msvcp_win.dll.so
rm lib/wine/i386-unix/msvcr100.dll.so
rm lib/wine/i386-unix/msvcr110.dll.so
rm lib/wine/i386-unix/msvcr120.dll.so
rm lib/wine/i386-unix/msvcr120_app.dll.so
rm lib/wine/i386-unix/msvcr70.dll.so
rm lib/wine/i386-unix/msvcr71.dll.so
rm lib/wine/i386-unix/msvcr80.dll.so
rm lib/wine/i386-unix/msvcr90.dll.so
rm lib/wine/i386-unix/msvcrt20.dll.so
rm lib/wine/i386-unix/msvcrt40.dll.so
rm lib/wine/i386-unix/msvcrtd.dll.so
rm lib/wine/i386-unix/msvdsp.dll.so
rm lib/wine/i386-unix/msvfw32.dll.so
rm lib/wine/i386-unix/msvidc32.dll.so
rm lib/wine/i386-unix/msvproc.dll.so
rm lib/wine/i386-unix/mswsock.dll.so
rm lib/wine/i386-unix/msxml.dll.so
rm lib/wine/i386-unix/msxml2.dll.so
rm lib/wine/i386-unix/msxml4.dll.so
rm lib/wine/i386-unix/msxml6.dll.so
rm lib/wine/i386-unix/mtxdm.dll.so
rm lib/wine/i386-unix/ncrypt.dll.so
rm lib/wine/i386-unix/nddeapi.dll.so
rm lib/wine/i386-unix/ndis.sys.so
rm lib/wine/i386-unix/net.exe.so
rm lib/wine/i386-unix/netapi32.so
rm lib/wine/i386-unix/netcfgx.dll.so
rm lib/wine/i386-unix/netio.sys.so
rm lib/wine/i386-unix/netprofm.dll.so
rm lib/wine/i386-unix/netsh.exe.so
rm lib/wine/i386-unix/netstat.exe.so
rm lib/wine/i386-unix/ngen.exe.so
rm lib/wine/i386-unix/ninput.dll.so
rm lib/wine/i386-unix/notepad.exe.so
rm lib/wine/i386-unix/npmshtml.dll.so
rm lib/wine/i386-unix/npptools.dll.so
rm lib/wine/i386-unix/nsiproxy.so
rm lib/wine/i386-unix/nsiproxy.sys.so
rm lib/wine/i386-unix/ntdsapi.dll.so
rm lib/wine/i386-unix/ntoskrnl.exe.so
rm lib/wine/i386-unix/ntprint.dll.so
rm lib/wine/i386-unix/objsel.dll.so
rm lib/wine/i386-unix/odbc32.dll.so
rm lib/wine/i386-unix/odbc32.so
rm lib/wine/i386-unix/odbcbcp.dll.so
rm lib/wine/i386-unix/odbccp32.dll.so
rm lib/wine/i386-unix/odbccu32.dll.so
rm lib/wine/i386-unix/oleacc.dll.so
rm lib/wine/i386-unix/olecli32.dll.so
rm lib/wine/i386-unix/oledb32.dll.so
rm lib/wine/i386-unix/oledlg.dll.so
rm lib/wine/i386-unix/olepro32.dll.so
rm lib/wine/i386-unix/olesvr32.dll.so
rm lib/wine/i386-unix/olethk32.dll.so
rm lib/wine/i386-unix/oleview.exe.so
rm lib/wine/i386-unix/opcservices.dll.so
rm lib/wine/i386-unix/opengl32.dll.so
rm lib/wine/i386-unix/opengl32.so
rm lib/wine/i386-unix/packager.dll.so
rm lib/wine/i386-unix/pdh.dll.so
rm lib/wine/i386-unix/photometadatahandler.dll.so
rm lib/wine/i386-unix/pidgen.dll.so
rm lib/wine/i386-unix/ping.exe.so
rm lib/wine/i386-unix/plugplay.exe.so
rm lib/wine/i386-unix/pnputil.exe.so
rm lib/wine/i386-unix/powershell.exe.so
rm lib/wine/i386-unix/powrprof.dll.so
rm lib/wine/i386-unix/presentationfontcache.exe.so
rm lib/wine/i386-unix/printui.dll.so
rm lib/wine/i386-unix/prntvpt.dll.so
rm lib/wine/i386-unix/profapi.dll.so
rm lib/wine/i386-unix/progman.exe.so
rm lib/wine/i386-unix/propsys.dll.so
rm lib/wine/i386-unix/pstorec.dll.so
rm lib/wine/i386-unix/pwrshplugin.dll.so
rm lib/wine/i386-unix/qasf.dll.so
rm lib/wine/i386-unix/qcap.dll.so
rm lib/wine/i386-unix/qcap.so
rm lib/wine/i386-unix/qdvd.dll.so
rm lib/wine/i386-unix/qedit.dll.so
rm lib/wine/i386-unix/qmgr.dll.so
rm lib/wine/i386-unix/qmgrprxy.dll.so
rm lib/wine/i386-unix/quartz.dll.so
rm lib/wine/i386-unix/query.dll.so
rm lib/wine/i386-unix/qwave.dll.so
rm lib/wine/i386-unix/rasapi32.dll.so
rm lib/wine/i386-unix/rasdlg.dll.so
rm lib/wine/i386-unix/reg.exe.so
rm lib/wine/i386-unix/regapi.dll.so
rm lib/wine/i386-unix/regasm.exe.so
rm lib/wine/i386-unix/regedit.exe.so
rm lib/wine/i386-unix/regini.exe.so
rm lib/wine/i386-unix/regsvcs.exe.so
rm lib/wine/i386-unix/regsvr32.exe.so
rm lib/wine/i386-unix/resampledmo.dll.so
rm lib/wine/i386-unix/resutils.dll.so
rm lib/wine/i386-unix/riched20.dll.so
rm lib/wine/i386-unix/riched32.dll.so
rm lib/wine/i386-unix/robocopy.exe.so
rm lib/wine/i386-unix/rometadata.dll.so
rm lib/wine/i386-unix/rpcss.exe.so
rm lib/wine/i386-unix/rsabase.dll.so
rm lib/wine/i386-unix/rstrtmgr.dll.so
rm lib/wine/i386-unix/rtutils.dll.so
rm lib/wine/i386-unix/rtworkq.dll.so
rm lib/wine/i386-unix/runas.exe.so
rm lib/wine/i386-unix/samlib.dll.so
rm lib/wine/i386-unix/sapi.dll.so
rm lib/wine/i386-unix/sas.dll.so
rm lib/wine/i386-unix/sc.exe.so
rm lib/wine/i386-unix/scarddlg.dll.so
rm lib/wine/i386-unix/scardsvr.dll.so
rm lib/wine/i386-unix/sccbase.dll.so
rm lib/wine/i386-unix/schannel.dll.so
rm lib/wine/i386-unix/schedsvc.dll.so
rm lib/wine/i386-unix/schtasks.exe.so
rm lib/wine/i386-unix/scrobj.dll.so
rm lib/wine/i386-unix/scrrun.dll.so
rm lib/wine/i386-unix/scsiport.sys.so
rm lib/wine/i386-unix/sdbinst.exe.so
rm lib/wine/i386-unix/secedit.exe.so
rm lib/wine/i386-unix/secur32.so
rm lib/wine/i386-unix/sensapi.dll.so
rm lib/wine/i386-unix/serialui.dll.so
rm lib/wine/i386-unix/servicemodelreg.exe.so
rm lib/wine/i386-unix/setx.exe.so
rm lib/wine/i386-unix/sfc_os.dll.so
rm lib/wine/i386-unix/shdocvw.dll.so
rm lib/wine/i386-unix/shfolder.dll.so
rm lib/wine/i386-unix/shutdown.exe.so
rm lib/wine/i386-unix/slbcsp.dll.so
rm lib/wine/i386-unix/slc.dll.so
rm lib/wine/i386-unix/snmpapi.dll.so
rm lib/wine/i386-unix/softpub.dll.so
rm lib/wine/i386-unix/sort.exe.so
rm lib/wine/i386-unix/spoolss.dll.so
rm lib/wine/i386-unix/spoolsv.exe.so
rm lib/wine/i386-unix/sppc.dll.so
rm lib/wine/i386-unix/srclient.dll.so
rm lib/wine/i386-unix/srvcli.dll.so
rm lib/wine/i386-unix/srvsvc.dll.so
rm lib/wine/i386-unix/sspicli.dll.so
rm lib/wine/i386-unix/start.exe.so
rm lib/wine/i386-unix/sti.dll.so
rm lib/wine/i386-unix/strmdll.dll.so
rm lib/wine/i386-unix/subst.exe.so
rm lib/wine/i386-unix/svchost.exe.so
rm lib/wine/i386-unix/svrapi.dll.so
rm lib/wine/i386-unix/sxs.dll.so
rm lib/wine/i386-unix/systeminfo.exe.so
rm lib/wine/i386-unix/t2embed.dll.so
rm lib/wine/i386-unix/tapi32.dll.so
rm lib/wine/i386-unix/taskkill.exe.so
rm lib/wine/i386-unix/tasklist.exe.so
rm lib/wine/i386-unix/taskmgr.exe.so
rm lib/wine/i386-unix/taskschd.dll.so
rm lib/wine/i386-unix/tbs.dll.so
rm lib/wine/i386-unix/tdh.dll.so
rm lib/wine/i386-unix/tdi.sys.so
rm lib/wine/i386-unix/termsv.exe.so
rm lib/wine/i386-unix/threadpoolwinrt.dll.so
rm lib/wine/i386-unix/timeout.exe.so
rm lib/wine/i386-unix/traffic.dll.so
rm lib/wine/i386-unix/twain_32.dll.so
rm lib/wine/i386-unix/twaindsm.dll.so
rm lib/wine/i386-unix/twinapi.appcore.dll.so
rm lib/wine/i386-unix/uianimation.dll.so
rm lib/wine/i386-unix/uiautomationcore.dll.so
rm lib/wine/i386-unix/uiribbon.dll.so
rm lib/wine/i386-unix/unicows.dll.so
rm lib/wine/i386-unix/uninstaller.exe.so
rm lib/wine/i386-unix/unlodctr.exe.so
rm lib/wine/i386-unix/updspapi.dll.so
rm lib/wine/i386-unix/url.dll.so
rm lib/wine/i386-unix/usbd.sys.so
rm lib/wine/i386-unix/userenv.dll.so
rm lib/wine/i386-unix/utildll.dll.so
rm lib/wine/i386-unix/uxtheme.dll.so
rm lib/wine/i386-unix/vbscript.dll.so
rm lib/wine/i386-unix/vccorlib140.dll.so
rm lib/wine/i386-unix/vcomp.dll.so
rm lib/wine/i386-unix/vcomp100.dll.so
rm lib/wine/i386-unix/vcomp110.dll.so
rm lib/wine/i386-unix/vcomp120.dll.so
rm lib/wine/i386-unix/vcomp140.dll.so
rm lib/wine/i386-unix/vcomp90.dll.so
rm lib/wine/i386-unix/vcruntime140.dll.so
rm lib/wine/i386-unix/vdmdbg.dll.so
rm lib/wine/i386-unix/vga.dll.so
rm lib/wine/i386-unix/vidreszr.dll.so
rm lib/wine/i386-unix/view.exe.so
rm lib/wine/i386-unix/virtdisk.dll.so
rm lib/wine/i386-unix/vssapi.dll.so
rm lib/wine/i386-unix/wbemdisp.dll.so
rm lib/wine/i386-unix/wbemprox.dll.so
rm lib/wine/i386-unix/wdscore.dll.so
rm lib/wine/i386-unix/webservices.dll.so
rm lib/wine/i386-unix/websocket.dll.so
rm lib/wine/i386-unix/wer.dll.so
rm lib/wine/i386-unix/wevtapi.dll.so
rm lib/wine/i386-unix/wevtsvc.dll.so
rm lib/wine/i386-unix/wevtutil.exe.so
rm lib/wine/i386-unix/where.exe.so
rm lib/wine/i386-unix/whoami.exe.so
rm lib/wine/i386-unix/wiaservc.dll.so
rm lib/wine/i386-unix/wimgapi.dll.so
rm lib/wine/i386-unix/winbio.dll.so
rm lib/wine/i386-unix/winbrand.dll.so
rm lib/wine/i386-unix/windows.applicationmodel.dll.so
rm lib/wine/i386-unix/windows.devices.bluetooth.dll.so
rm lib/wine/i386-unix/windows.devices.enumeration.dll.so
rm lib/wine/i386-unix/windows.devices.usb.dll.so
rm lib/wine/i386-unix/windows.gaming.input.dll.so
rm lib/wine/i386-unix/windows.gaming.ui.gamebar.dll.so
rm lib/wine/i386-unix/windows.globalization.dll.so
rm lib/wine/i386-unix/windows.media.devices.dll.so
rm lib/wine/i386-unix/windows.media.dll.so
rm lib/wine/i386-unix/windows.media.mediacontrol.dll.so
rm lib/wine/i386-unix/windows.media.playback.backgroundmediaplayer.dll.so
rm lib/wine/i386-unix/windows.media.playback.mediaplayer.dll.so
rm lib/wine/i386-unix/windows.media.speech.dll.so
rm lib/wine/i386-unix/windows.networking.connectivity.dll.so
rm lib/wine/i386-unix/windows.networking.dll.so
rm lib/wine/i386-unix/windows.networking.hostname.dll.so
rm lib/wine/i386-unix/windows.perception.stub.dll.so
rm lib/wine/i386-unix/windows.security.authentication.onlineid.dll.so
rm lib/wine/i386-unix/windows.security.credentials.ui.userconsentverifier.dll.so
rm lib/wine/i386-unix/windows.storage.applicationdata.dll.so
rm lib/wine/i386-unix/windows.storage.dll.so
rm lib/wine/i386-unix/windows.system.profile.systemid.dll.so
rm lib/wine/i386-unix/windows.system.profile.systemmanufacturers.dll.so
rm lib/wine/i386-unix/windows.ui.core.textinput.dll.so
rm lib/wine/i386-unix/windows.ui.dll.so
rm lib/wine/i386-unix/windows.ui.xaml.dll.so
rm lib/wine/i386-unix/windows.web.dll.so
rm lib/wine/i386-unix/windowscodecs.dll.so
rm lib/wine/i386-unix/windowscodecsext.dll.so
rm lib/wine/i386-unix/wine-preloader
rm lib/wine/i386-unix/winebrowser.exe.so
rm lib/wine/i386-unix/winebth.so
rm lib/wine/i386-unix/winebth.sys.so
rm lib/wine/i386-unix/winebus.so
rm lib/wine/i386-unix/winebus.sys.so
rm lib/wine/i386-unix/winecfg.exe.so
rm lib/wine/i386-unix/wineconsole.exe.so
rm lib/wine/i386-unix/winedbg.exe.so
rm lib/wine/i386-unix/winedevice.exe.so
rm lib/wine/i386-unix/winedmo.dll.so
rm lib/wine/i386-unix/winedmo.so
rm lib/wine/i386-unix/winefile.exe.so
rm lib/wine/i386-unix/winehid.sys.so
rm lib/wine/i386-unix/winemapi.dll.so
rm lib/wine/i386-unix/winemenubuilder.exe.so
rm lib/wine/i386-unix/winemine.exe.so
rm lib/wine/i386-unix/winemsibuilder.exe.so
rm lib/wine/i386-unix/winepath.exe.so
rm lib/wine/i386-unix/wineps.drv.so
rm lib/wine/i386-unix/wineps.so
rm lib/wine/i386-unix/winexinput.sys.so
rm lib/wine/i386-unix/wing32.dll.so
rm lib/wine/i386-unix/winhlp32.exe.so
rm lib/wine/i386-unix/winhttp.dll.so
rm lib/wine/i386-unix/winmgmt.exe.so
rm lib/wine/i386-unix/winmm.dll.so
rm lib/wine/i386-unix/winnls32.dll.so
rm lib/wine/i386-unix/winprint.dll.so
rm lib/wine/i386-unix/winspool.drv.so
rm lib/wine/i386-unix/winspool.so
rm lib/wine/i386-unix/winsta.dll.so
rm lib/wine/i386-unix/wintab32.dll.so
rm lib/wine/i386-unix/wintrust.dll.so
rm lib/wine/i386-unix/wintypes.dll.so
rm lib/wine/i386-unix/winusb.dll.so
rm lib/wine/i386-unix/winver.exe.so
rm lib/wine/i386-unix/wlanapi.dll.so
rm lib/wine/i386-unix/wlanui.dll.so
rm lib/wine/i386-unix/wldap32.dll.so
rm lib/wine/i386-unix/wldp.dll.so
rm lib/wine/i386-unix/wmadmod.dll.so
rm lib/wine/i386-unix/wmasf.dll.so
rm lib/wine/i386-unix/wmic.exe.so
rm lib/wine/i386-unix/wmilib.sys.so
rm lib/wine/i386-unix/wmiutils.dll.so
rm lib/wine/i386-unix/wmp.dll.so
rm lib/wine/i386-unix/wmphoto.dll.so
rm lib/wine/i386-unix/wmplayer.exe.so
rm lib/wine/i386-unix/wmvcore.dll.so
rm lib/wine/i386-unix/wmvdecod.dll.so
rm lib/wine/i386-unix/wnaspi32.dll.so
rm lib/wine/i386-unix/wofutil.dll.so
rm lib/wine/i386-unix/wordpad.exe.so
rm lib/wine/i386-unix/wpc.dll.so
rm lib/wine/i386-unix/write.exe.so
rm lib/wine/i386-unix/wscript.exe.so
rm lib/wine/i386-unix/wsdapi.dll.so
rm lib/wine/i386-unix/wshom.ocx.so
rm lib/wine/i386-unix/wsnmp32.dll.so
rm lib/wine/i386-unix/wsock32.dll.so
rm lib/wine/i386-unix/wtsapi32.dll.so
rm lib/wine/i386-unix/wuapi.dll.so
rm lib/wine/i386-unix/wuaueng.dll.so
rm lib/wine/i386-unix/wuauserv.exe.so
rm lib/wine/i386-unix/wusa.exe.so
rm lib/wine/i386-unix/xcopy.exe.so
rm lib/wine/i386-unix/xmllite.dll.so
rm lib/wine/i386-unix/xolehlp.dll.so
rm lib/wine/i386-unix/xpsprint.dll.so
rm lib/wine/i386-unix/xpssvcs.dll.so

# lib/i386-windows
rm lib/wine/i386-windows/xinput*
rm lib/wine/i386-windows/xaudio*
rm lib/wine/i386-windows/x3daudio*
rm lib/wine/i386-windows/xactengine*
rm lib/wine/i386-windows/xapofx*
rm lib/wine/i386-windows/*d3d*
rm lib/wine/i386-windows/*vulkan*
rm lib/wine/i386-windows/acledit.dll
rm lib/wine/i386-windows/aclui.dll
rm lib/wine/i386-windows/activeds.dll
rm lib/wine/i386-windows/activeds.tlb
rm lib/wine/i386-windows/actxprxy.dll
rm lib/wine/i386-windows/adsldp.dll
rm lib/wine/i386-windows/adsldpc.dll
rm lib/wine/i386-windows/amsi.dll
rm lib/wine/i386-windows/amstream.dll
rm lib/wine/i386-windows/apisetschema.dll
rm lib/wine/i386-windows/apphelp.dll
rm lib/wine/i386-windows/appwiz.cpl
rm lib/wine/i386-windows/appxdeploymentclient.dll
rm lib/wine/i386-windows/arp.exe
rm lib/wine/i386-windows/aspnet_regiis.exe
rm lib/wine/i386-windows/atl.dll
rm lib/wine/i386-windows/atl110.dll
rm lib/wine/i386-windows/atl80.dll
rm lib/wine/i386-windows/atl90.dll
rm lib/wine/i386-windows/atlthunk.dll
rm lib/wine/i386-windows/atmlib.dll
rm lib/wine/i386-windows/attrib.exe
rm lib/wine/i386-windows/authz.dll
rm lib/wine/i386-windows/avicap32.dll
rm lib/wine/i386-windows/avifil32.dll
rm lib/wine/i386-windows/avrt.dll
rm lib/wine/i386-windows/bcp47langs.dll
rm lib/wine/i386-windows/bcryptprimitives.dll
rm lib/wine/i386-windows/bluetoothapis.dll
rm lib/wine/i386-windows/browseui.dll
rm lib/wine/i386-windows/bthprops.cpl
rm lib/wine/i386-windows/cabarc.exe
rm lib/wine/i386-windows/cabinet.dll
rm lib/wine/i386-windows/cacls.exe
rm lib/wine/i386-windows/cards.dll
rm lib/wine/i386-windows/cdosys.dll
rm lib/wine/i386-windows/certutil.exe
rm lib/wine/i386-windows/cfgmgr32.dll
rm lib/wine/i386-windows/chcp.com
rm lib/wine/i386-windows/clock.exe
rm lib/wine/i386-windows/clusapi.dll
rm lib/wine/i386-windows/cmd.exe
rm lib/wine/i386-windows/cng.sys
rm lib/wine/i386-windows/colorcnv.dll
rm lib/wine/i386-windows/comcat.dll
rm lib/wine/i386-windows/comctl32.dll
rm lib/wine/i386-windows/comctl32_v6.dll
rm lib/wine/i386-windows/comdlg32.dll
rm lib/wine/i386-windows/compstui.dll
rm lib/wine/i386-windows/comsvcs.dll
rm lib/wine/i386-windows/concrt140.dll
rm lib/wine/i386-windows/connect.dll
rm lib/wine/i386-windows/control.exe
rm lib/wine/i386-windows/coremessaging.dll
rm lib/wine/i386-windows/credui.dll
rm lib/wine/i386-windows/crtdll.dll
rm lib/wine/i386-windows/cryptdlg.dll
rm lib/wine/i386-windows/cryptdll.dll
rm lib/wine/i386-windows/cryptext.dll
rm lib/wine/i386-windows/cryptnet.dll
rm lib/wine/i386-windows/cryptowinrt.dll
rm lib/wine/i386-windows/cryptsp.dll
rm lib/wine/i386-windows/cryptui.dll
rm lib/wine/i386-windows/cryptxml.dll
rm lib/wine/i386-windows/cscript.exe
rm lib/wine/i386-windows/ctapi32.dll
rm lib/wine/i386-windows/ctl3d32.dll
rm lib/wine/i386-windows/d2d1.dll
rm lib/wine/i386-windows/dataexchange.dll
rm lib/wine/i386-windows/davclnt.dll
rm lib/wine/i386-windows/dbgeng.dll
rm lib/wine/i386-windows/dbghelp.dll
rm lib/wine/i386-windows/dciman32.dll
rm lib/wine/i386-windows/dcomp.dll
rm lib/wine/i386-windows/ddraw.dll
rm lib/wine/i386-windows/ddrawex.dll
rm lib/wine/i386-windows/desk.cpl
rm lib/wine/i386-windows/devenum.dll
rm lib/wine/i386-windows/dhcpcsvc.dll
rm lib/wine/i386-windows/dhcpcsvc6.dll
rm lib/wine/i386-windows/dhtmled.ocx
rm lib/wine/i386-windows/diasymreader.dll
rm lib/wine/i386-windows/difxapi.dll
rm lib/wine/i386-windows/dinput.dll
rm lib/wine/i386-windows/dinput8.dll
rm lib/wine/i386-windows/directmanipulation.dll
rm lib/wine/i386-windows/dism.exe
rm lib/wine/i386-windows/dispex.dll
rm lib/wine/i386-windows/dllhost.exe
rm lib/wine/i386-windows/dmband.dll
rm lib/wine/i386-windows/dmcompos.dll
rm lib/wine/i386-windows/dmime.dll
rm lib/wine/i386-windows/dmloader.dll
rm lib/wine/i386-windows/dmscript.dll
rm lib/wine/i386-windows/dmstyle.dll
rm lib/wine/i386-windows/dmsynth.dll
rm lib/wine/i386-windows/dmusic.dll
rm lib/wine/i386-windows/dmusic32.dll
rm lib/wine/i386-windows/dplay.dll
rm lib/wine/i386-windows/dplaysvr.exe
rm lib/wine/i386-windows/dplayx.dll
rm lib/wine/i386-windows/dpnaddr.dll
rm lib/wine/i386-windows/dpnet.dll
rm lib/wine/i386-windows/dpnhpast.dll
rm lib/wine/i386-windows/dpnhupnp.dll
rm lib/wine/i386-windows/dpnlobby.dll
rm lib/wine/i386-windows/dpnsvr.exe
rm lib/wine/i386-windows/dpvoice.dll
rm lib/wine/i386-windows/dpvsetup.exe
rm lib/wine/i386-windows/dpwsockx.dll
rm lib/wine/i386-windows/drmclien.dll
rm lib/wine/i386-windows/dsdmo.dll
rm lib/wine/i386-windows/dsound.dll
rm lib/wine/i386-windows/dsquery.dll
rm lib/wine/i386-windows/dssenh.dll
rm lib/wine/i386-windows/dsuiext.dll
rm lib/wine/i386-windows/dswave.dll
rm lib/wine/i386-windows/dwmapi.dll
rm lib/wine/i386-windows/dwrite.dll
rm lib/wine/i386-windows/dx8vb.dll
rm lib/wine/i386-windows/dxcore.dll
rm lib/wine/i386-windows/dxdiag.exe
rm lib/wine/i386-windows/dxdiagn.dll
rm lib/wine/i386-windows/dxgi.dll
rm lib/wine/i386-windows/dxtrans.dll
rm lib/wine/i386-windows/dxva2.dll
rm lib/wine/i386-windows/eject.exe
rm lib/wine/i386-windows/esent.dll
rm lib/wine/i386-windows/evr.dll
rm lib/wine/i386-windows/expand.exe
rm lib/wine/i386-windows/explorer.exe
rm lib/wine/i386-windows/explorerframe.dll
rm lib/wine/i386-windows/extrac32.exe
rm lib/wine/i386-windows/faultrep.dll
rm lib/wine/i386-windows/fc.exe
rm lib/wine/i386-windows/feclient.dll
rm lib/wine/i386-windows/find.exe
rm lib/wine/i386-windows/findstr.exe
rm lib/wine/i386-windows/fltlib.dll
rm lib/wine/i386-windows/fltmgr.sys
rm lib/wine/i386-windows/fntcache.dll
rm lib/wine/i386-windows/fontsub.dll
rm lib/wine/i386-windows/fsutil.exe
rm lib/wine/i386-windows/fusion.dll
rm lib/wine/i386-windows/fwpuclnt.dll
rm lib/wine/i386-windows/gameinput.dll
rm lib/wine/i386-windows/gameux.dll
rm lib/wine/i386-windows/gamingtcui.dll
rm lib/wine/i386-windows/gdiplus.dll
rm lib/wine/i386-windows/geolocation.dll
rm lib/wine/i386-windows/glu32.dll
rm lib/wine/i386-windows/gpkcsp.dll
rm lib/wine/i386-windows/graphicscapture.dll
rm lib/wine/i386-windows/hal.dll
rm lib/wine/i386-windows/hh.exe
rm lib/wine/i386-windows/hhctrl.ocx
rm lib/wine/i386-windows/hid.dll
rm lib/wine/i386-windows/hidclass.sys
rm lib/wine/i386-windows/hidparse.sys
rm lib/wine/i386-windows/hlink.dll
rm lib/wine/i386-windows/hnetcfg.dll
rm lib/wine/i386-windows/hostname.exe
rm lib/wine/i386-windows/hrtfapo.dll
rm lib/wine/i386-windows/http.sys
rm lib/wine/i386-windows/httpapi.dll
rm lib/wine/i386-windows/hvsimanagementapi.dll
rm lib/wine/i386-windows/ia2comproxy.dll
rm lib/wine/i386-windows/icacls.exe
rm lib/wine/i386-windows/iccvid.dll
rm lib/wine/i386-windows/icinfo.exe
rm lib/wine/i386-windows/icmp.dll
rm lib/wine/i386-windows/icmui.dll
rm lib/wine/i386-windows/ieframe.dll
rm lib/wine/i386-windows/ieproxy.dll
rm lib/wine/i386-windows/iertutil.dll
rm lib/wine/i386-windows/iexplore.exe
rm lib/wine/i386-windows/imaadp32.acm
rm lib/wine/i386-windows/imm32.dll
rm lib/wine/i386-windows/inetcomm.dll
rm lib/wine/i386-windows/inetcpl.cpl
rm lib/wine/i386-windows/inetmib1.dll
rm lib/wine/i386-windows/infosoft.dll
rm lib/wine/i386-windows/initpki.dll
rm lib/wine/i386-windows/inkobj.dll
rm lib/wine/i386-windows/inseng.dll
rm lib/wine/i386-windows/ipconfig.exe
rm lib/wine/i386-windows/iprop.dll
rm lib/wine/i386-windows/ir50_32.dll
rm lib/wine/i386-windows/irprops.cpl
rm lib/wine/i386-windows/itircl.dll
rm lib/wine/i386-windows/itss.dll
rm lib/wine/i386-windows/joy.cpl
rm lib/wine/i386-windows/jscript.dll
rm lib/wine/i386-windows/jsproxy.dll
rm lib/wine/i386-windows/kerberos.dll
rm lib/wine/i386-windows/klist.exe
rm lib/wine/i386-windows/ksecdd.sys
rm lib/wine/i386-windows/ksproxy.ax
rm lib/wine/i386-windows/ksuser.dll
rm lib/wine/i386-windows/ktmw32.dll
rm lib/wine/i386-windows/l3codeca.acm
rm lib/wine/i386-windows/l3codecx.ax
rm lib/wine/i386-windows/light.msstyles
rm lib/wine/i386-windows/loadperf.dll
rm lib/wine/i386-windows/localspl.dll
rm lib/wine/i386-windows/localui.dll
rm lib/wine/i386-windows/lodctr.exe
rm lib/wine/i386-windows/lz32.dll
rm lib/wine/i386-windows/magnification.dll
rm lib/wine/i386-windows/makecab.exe
rm lib/wine/i386-windows/mapi32.dll
rm lib/wine/i386-windows/mapistub.dll
rm lib/wine/i386-windows/mciavi32.dll
rm lib/wine/i386-windows/mcicda.dll
rm lib/wine/i386-windows/mciqtz32.dll
rm lib/wine/i386-windows/mciseq.dll
rm lib/wine/i386-windows/mciwave.dll
rm lib/wine/i386-windows/mf.dll
rm lib/wine/i386-windows/mf3216.dll
rm lib/wine/i386-windows/mfasfsrcsnk.dll
rm lib/wine/i386-windows/mferror.dll
rm lib/wine/i386-windows/mfh264enc.dll
rm lib/wine/i386-windows/mfmediaengine.dll
rm lib/wine/i386-windows/mfmp4srcsnk.dll
rm lib/wine/i386-windows/mfplat.dll
rm lib/wine/i386-windows/mfplay.dll
rm lib/wine/i386-windows/mfreadwrite.dll
rm lib/wine/i386-windows/mfsrcsnk.dll
rm lib/wine/i386-windows/mgmtapi.dll
rm lib/wine/i386-windows/midimap.dll
rm lib/wine/i386-windows/mlang.dll
rm lib/wine/i386-windows/mmcndmgr.dll
rm lib/wine/i386-windows/mmdevapi.dll
rm lib/wine/i386-windows/mofcomp.exe
rm lib/wine/i386-windows/mouhid.sys
rm lib/wine/i386-windows/mountmgr.sys
rm lib/wine/i386-windows/mp3dmod.dll
rm lib/wine/i386-windows/mprapi.dll
rm lib/wine/i386-windows/msacm32.dll
rm lib/wine/i386-windows/msacm32.drv
rm lib/wine/i386-windows/msado15.dll
rm lib/wine/i386-windows/msadp32.acm
rm lib/wine/i386-windows/msasn1.dll
rm lib/wine/i386-windows/msauddecmft.dll
rm lib/wine/i386-windows/mscat32.dll
rm lib/wine/i386-windows/mscms.dll
rm lib/wine/i386-windows/mscorwks.dll
rm lib/wine/i386-windows/msctf.dll
rm lib/wine/i386-windows/msctfmonitor.dll
rm lib/wine/i386-windows/msctfp.dll
rm lib/wine/i386-windows/msdaps.dll
rm lib/wine/i386-windows/msdasql.dll
rm lib/wine/i386-windows/msdelta.dll
rm lib/wine/i386-windows/msdmo.dll
rm lib/wine/i386-windows/msdrm.dll
rm lib/wine/i386-windows/msftedit.dll
rm lib/wine/i386-windows/msg711.acm
rm lib/wine/i386-windows/msgsm32.acm
rm lib/wine/i386-windows/mshta.exe
rm lib/wine/i386-windows/mshtml.dll
rm lib/wine/i386-windows/mshtml.tlb
rm lib/wine/i386-windows/msi.dll
rm lib/wine/i386-windows/msidb.exe
rm lib/wine/i386-windows/msident.dll
rm lib/wine/i386-windows/msiexec.exe
rm lib/wine/i386-windows/msimg32.dll
rm lib/wine/i386-windows/msimsg.dll
rm lib/wine/i386-windows/msimtf.dll
rm lib/wine/i386-windows/msinfo32.exe
rm lib/wine/i386-windows/msisip.dll
rm lib/wine/i386-windows/msisys.ocx
rm lib/wine/i386-windows/msls31.dll
rm lib/wine/i386-windows/msmpeg2vdec.dll
rm lib/wine/i386-windows/msnet32.dll
rm lib/wine/i386-windows/mspatcha.dll
rm lib/wine/i386-windows/msports.dll
rm lib/wine/i386-windows/msrle32.dll
rm lib/wine/i386-windows/msscript.ocx
rm lib/wine/i386-windows/mssign32.dll
rm lib/wine/i386-windows/mssip32.dll
rm lib/wine/i386-windows/mstask.dll
rm lib/wine/i386-windows/msttsengine.dll
rm lib/wine/i386-windows/msvcirt.dll
rm lib/wine/i386-windows/msvcm80.dll
rm lib/wine/i386-windows/msvcm90.dll
rm lib/wine/i386-windows/msvcp100.dll
rm lib/wine/i386-windows/msvcp110.dll
rm lib/wine/i386-windows/msvcp120.dll
rm lib/wine/i386-windows/msvcp120_app.dll
rm lib/wine/i386-windows/msvcp140.dll
rm lib/wine/i386-windows/msvcp140_1.dll
rm lib/wine/i386-windows/msvcp140_2.dll
rm lib/wine/i386-windows/msvcp140_atomic_wait.dll
rm lib/wine/i386-windows/msvcp140_codecvt_ids.dll
rm lib/wine/i386-windows/msvcp60.dll
rm lib/wine/i386-windows/msvcp70.dll
rm lib/wine/i386-windows/msvcp71.dll
rm lib/wine/i386-windows/msvcp80.dll
rm lib/wine/i386-windows/msvcp90.dll
rm lib/wine/i386-windows/msvcp_win.dll
rm lib/wine/i386-windows/msvcr100.dll
rm lib/wine/i386-windows/msvcr110.dll
rm lib/wine/i386-windows/msvcr120.dll
rm lib/wine/i386-windows/msvcr120_app.dll
rm lib/wine/i386-windows/msvcr70.dll
rm lib/wine/i386-windows/msvcr71.dll
rm lib/wine/i386-windows/msvcr80.dll
rm lib/wine/i386-windows/msvcr90.dll
rm lib/wine/i386-windows/msvcrt20.dll
rm lib/wine/i386-windows/msvcrt40.dll
rm lib/wine/i386-windows/msvcrtd.dll
rm lib/wine/i386-windows/msvdsp.dll
rm lib/wine/i386-windows/msvfw32.dll
rm lib/wine/i386-windows/msvidc32.dll
rm lib/wine/i386-windows/msvproc.dll
rm lib/wine/i386-windows/mswsock.dll
rm lib/wine/i386-windows/msxml.dll
rm lib/wine/i386-windows/msxml2.dll
rm lib/wine/i386-windows/msxml4.dll
rm lib/wine/i386-windows/msxml6.dll
rm lib/wine/i386-windows/mtxdm.dll
rm lib/wine/i386-windows/ncrypt.dll
rm lib/wine/i386-windows/nddeapi.dll
rm lib/wine/i386-windows/ndis.sys
rm lib/wine/i386-windows/net.exe
rm lib/wine/i386-windows/netcfgx.dll
rm lib/wine/i386-windows/netio.sys
rm lib/wine/i386-windows/netprofm.dll
rm lib/wine/i386-windows/netsh.exe
rm lib/wine/i386-windows/netstat.exe
rm lib/wine/i386-windows/ngen.exe
rm lib/wine/i386-windows/ninput.dll
rm lib/wine/i386-windows/normaliz.dll
rm lib/wine/i386-windows/notepad.exe
rm lib/wine/i386-windows/npmshtml.dll
rm lib/wine/i386-windows/npptools.dll
rm lib/wine/i386-windows/nsiproxy.sys
rm lib/wine/i386-windows/ntdll.dll
rm lib/wine/i386-windows/ntdsapi.dll
rm lib/wine/i386-windows/ntoskrnl.exe
rm lib/wine/i386-windows/ntprint.dll
rm lib/wine/i386-windows/objsel.dll
rm lib/wine/i386-windows/odbc32.dll
rm lib/wine/i386-windows/odbcbcp.dll
rm lib/wine/i386-windows/odbccp32.dll
rm lib/wine/i386-windows/odbccu32.dll
rm lib/wine/i386-windows/oleacc.dll
rm lib/wine/i386-windows/olecli32.dll
rm lib/wine/i386-windows/oledb32.dll
rm lib/wine/i386-windows/oledlg.dll
rm lib/wine/i386-windows/olepro32.dll
rm lib/wine/i386-windows/olesvr32.dll
rm lib/wine/i386-windows/olethk32.dll
rm lib/wine/i386-windows/oleview.exe
rm lib/wine/i386-windows/opcservices.dll
rm lib/wine/i386-windows/opengl32.dll
rm lib/wine/i386-windows/packager.dll
rm lib/wine/i386-windows/pdh.dll
rm lib/wine/i386-windows/photometadatahandler.dll
rm lib/wine/i386-windows/pidgen.dll
rm lib/wine/i386-windows/ping.exe
rm lib/wine/i386-windows/plugplay.exe
rm lib/wine/i386-windows/pnputil.exe
rm lib/wine/i386-windows/powershell.exe
rm lib/wine/i386-windows/powrprof.dll
rm lib/wine/i386-windows/presentationfontcache.exe
rm lib/wine/i386-windows/printui.dll
rm lib/wine/i386-windows/prntvpt.dll
rm lib/wine/i386-windows/profapi.dll
rm lib/wine/i386-windows/progman.exe
rm lib/wine/i386-windows/propsys.dll
rm lib/wine/i386-windows/pstorec.dll
rm lib/wine/i386-windows/pwrshplugin.dll
rm lib/wine/i386-windows/qasf.dll
rm lib/wine/i386-windows/qcap.dll
rm lib/wine/i386-windows/qdvd.dll
rm lib/wine/i386-windows/qedit.dll
rm lib/wine/i386-windows/qmgr.dll
rm lib/wine/i386-windows/qmgrprxy.dll
rm lib/wine/i386-windows/quartz.dll
rm lib/wine/i386-windows/query.dll
rm lib/wine/i386-windows/qwave.dll
rm lib/wine/i386-windows/rasapi32.dll
rm lib/wine/i386-windows/rasdlg.dll
rm lib/wine/i386-windows/reg.exe
rm lib/wine/i386-windows/regapi.dll
rm lib/wine/i386-windows/regasm.exe
rm lib/wine/i386-windows/regedit.exe
rm lib/wine/i386-windows/regini.exe
rm lib/wine/i386-windows/regsvcs.exe
rm lib/wine/i386-windows/regsvr32.exe
rm lib/wine/i386-windows/resampledmo.dll
rm lib/wine/i386-windows/resutils.dll
rm lib/wine/i386-windows/riched20.dll
rm lib/wine/i386-windows/riched32.dll
rm lib/wine/i386-windows/robocopy.exe
rm lib/wine/i386-windows/rometadata.dll
rm lib/wine/i386-windows/rpcss.exe
rm lib/wine/i386-windows/rsabase.dll
rm lib/wine/i386-windows/rstrtmgr.dll
rm lib/wine/i386-windows/rtutils.dll
rm lib/wine/i386-windows/rtworkq.dll
rm lib/wine/i386-windows/runas.exe
rm lib/wine/i386-windows/rundll32.exe
rm lib/wine/i386-windows/samlib.dll
rm lib/wine/i386-windows/sapi.dll
rm lib/wine/i386-windows/sas.dll
rm lib/wine/i386-windows/sc.exe
rm lib/wine/i386-windows/scarddlg.dll
rm lib/wine/i386-windows/scardsvr.dll
rm lib/wine/i386-windows/sccbase.dll
rm lib/wine/i386-windows/schannel.dll
rm lib/wine/i386-windows/schedsvc.dll
rm lib/wine/i386-windows/schtasks.exe
rm lib/wine/i386-windows/scrobj.dll
rm lib/wine/i386-windows/scrrun.dll
rm lib/wine/i386-windows/scsiport.sys
rm lib/wine/i386-windows/sdbinst.exe
rm lib/wine/i386-windows/secedit.exe
rm lib/wine/i386-windows/security.dll
rm lib/wine/i386-windows/sensapi.dll
rm lib/wine/i386-windows/serialui.dll
rm lib/wine/i386-windows/servicemodelreg.exe
rm lib/wine/i386-windows/services.exe
rm lib/wine/i386-windows/setx.exe
rm lib/wine/i386-windows/sfc.dll
rm lib/wine/i386-windows/sfc_os.dll
rm lib/wine/i386-windows/shdoclc.dll
rm lib/wine/i386-windows/shdocvw.dll
rm lib/wine/i386-windows/shfolder.dll
rm lib/wine/i386-windows/shutdown.exe
rm lib/wine/i386-windows/slbcsp.dll
rm lib/wine/i386-windows/slc.dll
rm lib/wine/i386-windows/snmpapi.dll
rm lib/wine/i386-windows/softpub.dll
rm lib/wine/i386-windows/sort.exe
rm lib/wine/i386-windows/spoolss.dll
rm lib/wine/i386-windows/spoolsv.exe
rm lib/wine/i386-windows/sppc.dll
rm lib/wine/i386-windows/srclient.dll
rm lib/wine/i386-windows/srvcli.dll
rm lib/wine/i386-windows/srvsvc.dll
rm lib/wine/i386-windows/sspicli.dll
rm lib/wine/i386-windows/start.exe
rm lib/wine/i386-windows/stdole2.tlb
rm lib/wine/i386-windows/stdole32.tlb
rm lib/wine/i386-windows/sti.dll
rm lib/wine/i386-windows/strmdll.dll
rm lib/wine/i386-windows/subst.exe
rm lib/wine/i386-windows/svchost.exe
rm lib/wine/i386-windows/svrapi.dll
rm lib/wine/i386-windows/sxs.dll
rm lib/wine/i386-windows/systeminfo.exe
rm lib/wine/i386-windows/t2embed.dll
rm lib/wine/i386-windows/tapi32.dll
rm lib/wine/i386-windows/taskkill.exe
rm lib/wine/i386-windows/tasklist.exe
rm lib/wine/i386-windows/taskmgr.exe
rm lib/wine/i386-windows/taskschd.dll
rm lib/wine/i386-windows/tbs.dll
rm lib/wine/i386-windows/tdh.dll
rm lib/wine/i386-windows/tdi.sys
rm lib/wine/i386-windows/termsv.exe
rm lib/wine/i386-windows/threadpoolwinrt.dll
rm lib/wine/i386-windows/timeout.exe
rm lib/wine/i386-windows/traffic.dll
rm lib/wine/i386-windows/twain_32.dll
rm lib/wine/i386-windows/twaindsm.dll
rm lib/wine/i386-windows/twinapi.appcore.dll
rm lib/wine/i386-windows/tzres.dll
rm lib/wine/i386-windows/uianimation.dll
rm lib/wine/i386-windows/uiautomationcore.dll
rm lib/wine/i386-windows/uiribbon.dll
rm lib/wine/i386-windows/unicows.dll
rm lib/wine/i386-windows/uninstaller.exe
rm lib/wine/i386-windows/unlodctr.exe
rm lib/wine/i386-windows/updspapi.dll
rm lib/wine/i386-windows/url.dll
rm lib/wine/i386-windows/usbd.sys
rm lib/wine/i386-windows/userenv.dll
rm lib/wine/i386-windows/usp10.dll
rm lib/wine/i386-windows/utildll.dll
rm lib/wine/i386-windows/uxtheme.dll
rm lib/wine/i386-windows/vbscript.dll
rm lib/wine/i386-windows/vccorlib140.dll
rm lib/wine/i386-windows/vcomp.dll
rm lib/wine/i386-windows/vcomp100.dll
rm lib/wine/i386-windows/vcomp110.dll
rm lib/wine/i386-windows/vcomp120.dll
rm lib/wine/i386-windows/vcomp140.dll
rm lib/wine/i386-windows/vcomp90.dll
rm lib/wine/i386-windows/vcruntime140.dll
rm lib/wine/i386-windows/vdmdbg.dll
rm lib/wine/i386-windows/vga.dll
rm lib/wine/i386-windows/vidreszr.dll
rm lib/wine/i386-windows/view.exe
rm lib/wine/i386-windows/virtdisk.dll
rm lib/wine/i386-windows/vssapi.dll
rm lib/wine/i386-windows/wbemdisp.dll
rm lib/wine/i386-windows/wbemprox.dll
rm lib/wine/i386-windows/wdscore.dll
rm lib/wine/i386-windows/webservices.dll
rm lib/wine/i386-windows/websocket.dll
rm lib/wine/i386-windows/wer.dll
rm lib/wine/i386-windows/wevtapi.dll
rm lib/wine/i386-windows/wevtsvc.dll
rm lib/wine/i386-windows/wevtutil.exe
rm lib/wine/i386-windows/where.exe
rm lib/wine/i386-windows/whoami.exe
rm lib/wine/i386-windows/wiaservc.dll
rm lib/wine/i386-windows/wimgapi.dll
rm lib/wine/i386-windows/winbio.dll
rm lib/wine/i386-windows/winbrand.dll
rm lib/wine/i386-windows/windows.applicationmodel.dll
rm lib/wine/i386-windows/windows.devices.bluetooth.dll
rm lib/wine/i386-windows/windows.devices.enumeration.dll
rm lib/wine/i386-windows/windows.devices.usb.dll
rm lib/wine/i386-windows/windows.gaming.input.dll
rm lib/wine/i386-windows/windows.gaming.ui.gamebar.dll
rm lib/wine/i386-windows/windows.globalization.dll
rm lib/wine/i386-windows/windows.media.devices.dll
rm lib/wine/i386-windows/windows.media.dll
rm lib/wine/i386-windows/windows.media.mediacontrol.dll
rm lib/wine/i386-windows/windows.media.playback.backgroundmediaplayer.dll
rm lib/wine/i386-windows/windows.media.playback.mediaplayer.dll
rm lib/wine/i386-windows/windows.media.speech.dll
rm lib/wine/i386-windows/windows.networking.connectivity.dll
rm lib/wine/i386-windows/windows.networking.dll
rm lib/wine/i386-windows/windows.networking.hostname.dll
rm lib/wine/i386-windows/windows.perception.stub.dll
rm lib/wine/i386-windows/windows.security.authentication.onlineid.dll
rm lib/wine/i386-windows/windows.security.credentials.ui.userconsentverifier.dll
rm lib/wine/i386-windows/windows.storage.applicationdata.dll
rm lib/wine/i386-windows/windows.storage.dll
rm lib/wine/i386-windows/windows.system.profile.systemid.dll
rm lib/wine/i386-windows/windows.system.profile.systemmanufacturers.dll
rm lib/wine/i386-windows/windows.ui.core.textinput.dll
rm lib/wine/i386-windows/windows.ui.dll
rm lib/wine/i386-windows/windows.ui.xaml.dll
rm lib/wine/i386-windows/windows.web.dll
rm lib/wine/i386-windows/windowscodecs.dll
rm lib/wine/i386-windows/windowscodecsext.dll
rm lib/wine/i386-windows/wineboot.exe
rm lib/wine/i386-windows/winebrowser.exe
rm lib/wine/i386-windows/winebth.sys
rm lib/wine/i386-windows/winebus.sys
rm lib/wine/i386-windows/winecfg.exe
rm lib/wine/i386-windows/wineconsole.exe
rm lib/wine/i386-windows/winedbg.exe
rm lib/wine/i386-windows/winedevice.exe
rm lib/wine/i386-windows/winedmo.dll
rm lib/wine/i386-windows/winefile.exe
rm lib/wine/i386-windows/winehid.sys
rm lib/wine/i386-windows/winemapi.dll
rm lib/wine/i386-windows/winemenubuilder.exe
rm lib/wine/i386-windows/winemine.exe
rm lib/wine/i386-windows/winemsibuilder.exe
rm lib/wine/i386-windows/winepath.exe
rm lib/wine/i386-windows/wineps.drv
rm lib/wine/i386-windows/winexinput.sys
rm lib/wine/i386-windows/wing32.dll
rm lib/wine/i386-windows/winhlp32.exe
rm lib/wine/i386-windows/winhttp.dll
rm lib/wine/i386-windows/winmgmt.exe
rm lib/wine/i386-windows/winmm.dll
rm lib/wine/i386-windows/winnls32.dll
rm lib/wine/i386-windows/winprint.dll
rm lib/wine/i386-windows/winspool.drv
rm lib/wine/i386-windows/winsta.dll
rm lib/wine/i386-windows/wintab32.dll
rm lib/wine/i386-windows/wintrust.dll
rm lib/wine/i386-windows/wintypes.dll
rm lib/wine/i386-windows/winusb.dll
rm lib/wine/i386-windows/winver.exe
rm lib/wine/i386-windows/wlanapi.dll
rm lib/wine/i386-windows/wlanui.dll
rm lib/wine/i386-windows/wldap32.dll
rm lib/wine/i386-windows/wldp.dll
rm lib/wine/i386-windows/wmadmod.dll
rm lib/wine/i386-windows/wmasf.dll
rm lib/wine/i386-windows/wmi.dll
rm lib/wine/i386-windows/wmic.exe
rm lib/wine/i386-windows/wmilib.sys
rm lib/wine/i386-windows/wmiutils.dll
rm lib/wine/i386-windows/wmp.dll
rm lib/wine/i386-windows/wmphoto.dll
rm lib/wine/i386-windows/wmplayer.exe
rm lib/wine/i386-windows/wmvcore.dll
rm lib/wine/i386-windows/wmvdecod.dll
rm lib/wine/i386-windows/wnaspi32.dll
rm lib/wine/i386-windows/wofutil.dll
rm lib/wine/i386-windows/wordpad.exe
rm lib/wine/i386-windows/wpc.dll
rm lib/wine/i386-windows/write.exe
rm lib/wine/i386-windows/wscript.exe
rm lib/wine/i386-windows/wsdapi.dll
rm lib/wine/i386-windows/wshom.ocx
rm lib/wine/i386-windows/wsnmp32.dll
rm lib/wine/i386-windows/wsock32.dll
rm lib/wine/i386-windows/wtsapi32.dll
rm lib/wine/i386-windows/wuapi.dll
rm lib/wine/i386-windows/wuaueng.dll
rm lib/wine/i386-windows/wuauserv.exe
rm lib/wine/i386-windows/wusa.exe
rm lib/wine/i386-windows/xcopy.exe
rm lib/wine/i386-windows/xmllite.dll
rm lib/wine/i386-windows/xolehlp.dll
rm lib/wine/i386-windows/xpsprint.dll
rm lib/wine/i386-windows/xpssvcs.dll

# Clear build output
rm -rf /app/build

popd
